# Full benchmark configuration
# Run: python -m src.benchmarking.cli run --config benchmark_configs/scibench_full.yaml
# Warning: This will take several hours to complete

batch_size: 692                   # All problems
random_seed: 42
skip_image_problems: true
timeout_per_problem: 300
checkpoint_frequency: 10          # Save every 10 problems
output_dir: benchmark_results
verbose: true
numeric_tolerance: 0.01
allow_unit_conversion: true
